version: '3.3'
volumes:
  pg_data:
  static:
  media:
services:
  db:
    image: postgres:13
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data
  backend:
    image: namari39/foodgram_backend
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data
      - media:/app/media/
      - static:/backend_static
    depends_on:
      - db
  frontend:
    container_name: foodgram-front
    image: namari39/foodgram_frontend
    command: cp -r /app/build/. /static/
    volumes:
      - static:/static
  nginx:
    container_name: foodgram-proxy
    image: namari39/foodgram_gateway
    ports:
      - "6000:80"
    volumes:
      - static:/static
      - media:/app/media/
    depends_on:
      - backend
      - frontend