version: '3.3'
volumes:
  pg_data:
  static:
  media:
services:
  db:
    image: postgres:13
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data
  backend:
    build: ../backend/
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data
      - media:/app/media/
      - static:/backend_static
  frontend:
    container_name: foodgram-front
    build: ../frontend
    command: cp -r /app/build/. /static/
    volumes:
      - static:/static
  nginx:
    container_name: foodgram-proxy
    build: .
    env_file: .env
    ports:
      - "80:80"
    volumes:
      - static:/static
      - media:/app/media/
