# Generated by Django 3.2 on 2025-01-16 11:30

from django.db import migrations
import users.managers


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', users.managers.SuperUserManager()),
            ],
        ),
    ]
